# Generated by Django 4.2.27 on 2026-01-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('HOSPITAL', 'Hospital Admin'), ('JPO', 'Junior Personnel Officer'), ('PO', 'Personnel Officer'), ('AS', 'Asist Sectory'), ('GMM', 'General Medical &Personal'), ('CGM', 'Chief General Manager '), ('JS', 'JOINT SECTROY '), ('DIRECTOR', 'DIRECTOR_HRD'), ('CUSTOMER_ADMIN', 'Customer Admin')], max_length=20),
        ),
    ]
