# Generated by Django 4.2.27 on 2026-01-20 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospitals', '0004_bill_created_by_bill_gst_number_and_more'),
        ('accounts', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__username'], 'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(blank=True, help_text='Job title or designation', max_length=100, verbose_name='designation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Required only for Hospital Admin role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='hospitals.hospital', verbose_name='associated hospital'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=15, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('HOSPITAL', 'Hospital Admin'), ('JPO', 'Junior Personnel Officer'), ('PO', 'Personnel Officer'), ('AS', 'Assistant Secretary'), ('GMM', 'General Medical & Personal'), ('CGM', 'Chief General Manager'), ('JS', 'Joint Secretary'), ('DIRECTOR', 'Director HRD'), ('CUSTOMER_ADMIN', 'Customer Admin')], default='JPO', max_length=20, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='accounts_us_role_e16858_idx'),
        ),
    ]
