# Generated by Django 4.2.27 on 2026-01-18 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='cc_card_detail',
            field=models.CharField(blank=True, help_text='Manual entry for CC Card', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='cc_card_file',
            field=models.FileField(blank=True, null=True, upload_to='bills/cc_cards/'),
        ),
        migrations.AddField(
            model_name='bill',
            name='discharge_summary_detail',
            field=models.CharField(blank=True, help_text='Manual entry for Discharge Summary', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='discharge_summary_file',
            field=models.FileField(blank=True, null=True, upload_to='bills/discharge_summaries/'),
        ),
        migrations.AddField(
            model_name='bill',
            name='id_card_detail',
            field=models.CharField(blank=True, help_text='Manual entry for ID Card', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='id_card_file',
            field=models.FileField(blank=True, null=True, upload_to='bills/id_cards/'),
        ),
        migrations.AddField(
            model_name='bill',
            name='tgnpdcl_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='category',
            field=models.CharField(blank=True, help_text='Hospital Category', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='hospital',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Pin Code'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Serial Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.TextField(verbose_name='Hospital Address'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='cin_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='CIN Number'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='code',
            field=models.CharField(help_text='Hospital Code', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='GST Number'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PAN Number'),
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='bills/supporting_docs/')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hospitals.bill')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospitals.service')),
            ],
        ),
    ]
