# Generated by Django 4.2.27 on 2026-01-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_bill_bill_date_bill_bill_number_bill_cc_card_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='base_rate_tier1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='base_rate_tier2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
