# Generated by Django 4.2.27 on 2026-01-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_bill_created_by_bill_gst_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
