# Generated by Django 4.2.27 on 2026-02-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_alter_bill_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='claim_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
