# Generated by Django 4.2.27 on 2026-01-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvallog',
            name='action',
            field=models.CharField(choices=[('FORWARD', 'Forward'), ('REJECT', 'Reject'), ('REJECT_RECOMMENDED', 'Submitted for Rejection'), ('APPROVE', 'Approve (Final)'), ('CLARIFY', 'Seek Clarification'), ('RESPOND', 'Respond to Clarification')], max_length=20),
        ),
    ]
